### ISSUE TITLE
Line graph. Add more information to the legend to explain what the different colours refer to

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biologging-sensor-client#93]
from jira https://biologging-data-lu.atlassian.net/jira/software/projects/BIOSENSOR/boards/1/backlog?selectedIssue=BIOSENSOR-128

Debora : "Snipe, activity: need a legend for the colours. Maybe also a axis legend telling the date interval shown – i.e. what the width of the squares is along the y. also not clear whether the colourful figure is for one or several animals?

In the activity score (Y) by time (x) figure below scores of 5 animals will be shown. Would be good to add a note (same goes for animal in the position map) that the different colours/numbers refer to individual animals. It’s a bit mysterious now ;-)

and for the pressure and temperature and altitude figures (e.g snipe data): similar to above: the continues time record number legend is not much useful. And explain that diffr colours/numbers are individual animals."

**Comment by mathieuLU** [comment]
@blacksparrowhawk yes more legend is required for the activity
please let me know what you would want here
![Screenshot from 2024-08-13 10-19-22](https://github.com/user-attachments/assets/2677ef4c-dce4-4945-a178-073373b98b16)

**Comment by DeboraArlt** [comment]
Looking at the diagrams now - same as commented for map and temperature: would be good with a more user friendly title/header then the current - which I think is the sensorType(?). For a user it would be better with something like "activity data" instead of Acceleration, and "Altitude" or  "Altitude data" instad of Altimeter. I also see that y-axis legend says "Altimeter (meters)" but should rather be "altitude (meters)".

For the activity data: Maybe need a short text that explains briefly how to read the diagram, e.g. good to know that one row is two consecutive days and the next row starts with the same day as the second day from the row above. @blacksparrowhawk can you privide some text? or ask Åke? I am thinking of something that you would write in a paper that would explain what is in the diagram and how to read it. Include information about that width of squares is time unit 1 hour (?), and that colour intensity is correlated to activity intensity(?).

**Comment by mathieuLU** [comment]
status of the expected views for the line graphs

![Screenshot from 2024-09-13 17-47-08](https://github.com/user-attachments/assets/c170289a-dd78-424d-a9d9-00ff4ea080d5)
![Screenshot from 2024-09-13 17-47-13](https://github.com/user-attachments/assets/274c58b9-6a30-4fcb-9513-de12baf75869)
![Screenshot from 2024-09-13 17-47-18](https://github.com/user-attachments/assets/9ae91ed4-9531-43ca-ac44-1343e0f2d321)
![Screenshot from 2024-09-13 17-47-24](https://github.com/user-attachments/assets/3d44ba07-861f-4331-8e1b-2fd666d70b74)

**Comment by DeboraArlt** [comment]
I think we discussed this some time ago - whether we want to display the name of the sensor type (e.g. altimeter) or what is measured (e.g. altitude (in meters)). At that time I hade no clear preference. But now seeing this in use it feels much better if we could use "what is measured" here. Like I wrote in the suggested texts in the ppt: instead of thermometer -> temperature, instead of altimeter -> altitude.
Thermometer .... is not wrong, but sounds awkward.

**Comment by DeboraArlt** [comment]
5 lines/tracks, and 50 points - ok for me! easy enough to change later. or perhaps already now change to 4 lines/tracks? in the example above with 5 it looks already quite cluttered. but 50 points is definitely ok (fewer will look boring, and more wil get too dense)

**Comment by DeboraArlt** [comment]
for the graph titles: tricky. sensortype "works" but I don't like it. sensortype is good to have as technical specification in the datamodel, but not really user friendly for visualisation. even though users are researchers and can work it out, for example "Thermometer" is just an awkward title. 
A compromise could be "[sensortype] data" with the [] marking the dynamic element, so for example title "Thermometer data", or "GPS data", or "Accelerometer data".

But Ideally I would like to have titles lik "Temperature", Animal tracks", Acceleration".

maybe we need to add a property like "sensor data display name" because neither sensorType or "valuesMeasured" work well as titles for the diagrams/figures. I have added some exmples to try this out here https://docs.google.com/spreadsheets/d/1r1v1YtqjMA3FkH4SUKX61n8IsCpKBA5M7OxeD8V0BP0/edit?gid=0#gid=0

**Comment by mathieuLU** [comment]
ok i found the way to display it.
So we have different options. Only the value measured (temperature, altitude, etc) or a bit more info with sensortype + value
let me know

![Screenshot from 2024-09-25 14-13-03](https://github.com/user-attachments/assets/ff4b8b2d-7dd2-49fe-a599-a586ac1b0812)
![Screenshot from 2024-09-25 14-13-10](https://github.com/user-attachments/assets/f8d22a4e-7b6e-4cb5-95c2-2a49a1e3f51b)
![Screenshot from 2024-09-25 14-13-30](https://github.com/user-attachments/assets/1e627f5e-164e-4e70-8982-d149243cebe5)

**Comment by DeboraArlt** [comment]
I would prefer "temperature", but if it is easier I can live with "Thermometer data". - it is either temperature (the values) or thermometer data that can be seen in the graph. (only "thermometer" would be "wrong" because it's not a thermometer that can be seen in the graph)

similar for the others:
preference "altitude", or alternatively ok with "Altimeter data"
preference "activity", or alternatively ok with "Accelerometer data"
preference "animal track" or "GPS positions", but NOT ok with "Geographic sperical coordiate system" - because that's not what can be seen on the map

**Comment by mathieuLU** [comment]
fixed with https://github.com/biodiversitydata-se/biologging-sensor-client/commit/c29461d165cdc950d2a9a8dabed556358e47ca2a !

**Comment by mathieuLU** [comment]
The value Measured is supposed to be displayed as well in the Y axis and the legend (temperature instead of theromemeter)

**Comment by mathieuLU** [comment]
the animal ID is supposed to be used instead of the tagID in the legend

**Comment by mathieuLU** [comment]
updated 
![Screenshot from 2024-10-08 15-00-16](https://github.com/user-attachments/assets/2686324b-4942-47a2-9272-3cc3931d371f)

**Comment by DeboraArlt** [comment]
Teext: should be changed to "5 animals (animal ID in legend)" now?

**Comment by mathieuLU** [comment]
fixed with https://github.com/biodiversitydata-se/biologging-sensor-client/commit/68863d19545abc5806d662bb67089838d593c974

**Comment by DeboraArlt** [comment]
yes, can be closed.
